/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        heading: ["Unbounded", "ui-sans-serif", "system-ui"],
        body: ["Outfit", "ui-sans-serif", "system-ui"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        arena: {
          bg: "#070707",
          surface: "#121212",
          panel: "#1A1A1A",
          border: "#2A2A2A",
          text: "#FFFFFF",
          muted: "#A0A0A0",
          dim: "#666666",
          yellow: "#FFB800",
          yellowHover: "#FFD147",
          red: "#FF3B30",
          blue: "#007AFF",
          green: "#00FF66",
        },
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        flash: { "0%": { backgroundColor: "#FFB800" }, "100%": { backgroundColor: "transparent" } },
        scanline: { "0%": { transform: "translateY(-100%)" }, "100%": { transform: "translateY(100vh)" } },
        pulse_glow: { "0%, 100%": { boxShadow: "0 0 0 0 rgba(255, 184, 0, 0.7)" }, "50%": { boxShadow: "0 0 0 8px rgba(255, 184, 0, 0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        flash: "flash 0.6s ease-out",
        scanline: "scanline 6s linear infinite",
        pulseGlow: "pulse_glow 2s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
